language: php

php:
    - 5.6
    - "7.0"
    - "7.1"
    - hhvm
    - nightly



sudo: false



git:
    submodules: false



addons:
    apt:
        packages:
            #- php-codesniffer
            #- phpmd
            #- shellcheck



matrix:
    allow_failures:
        #- php: "7.0"
        #- php: "7.1"
        - php: nightly
        - php: hhvm


env:
  global:
    - CC_TEST_REPORTER_ID=5c878564db8b30478c80b34d6a237675fd16fd7872877fbc4d90279f35ee4b9e


before_script:
    - make install
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build


script:
    - make check
    - make test


after_script:
    - ./cc-test-reporter after-build -d -t clover --exit-code $TRAVIS_TEST_RESULT


# notifications:
#     irc: "irc.freenode.org#dbwebb"
#     urls:
#       - https://webhooks.gitter.im/e/6e4660b0024de67de0af
#     on_success: change  # options: [always|never|change] default: always
#     on_failure: always  # options: [always|never|change] default: always
#     on_start: never     # options: [always|never|change] default: always
